class StringRes {
  static const String chooseBus = '选择公交';
  static const String chooseDir = '选择方向';
  static const String chooseStation = '选择站点';
  static const String queryBus = '查询';
  static const String saveBusLine = '保存路线';
  static const String choose_bus_hint = '请选择公交路线';
  static const String choose_dir_hint = '请选择方向';
  static const String choose_selfStop_hint = '请选择所在站点';
  static const String save_successed = '保存成功';
  static const String next_step = '下一步';
  static const String confirm = '确定';
  static const String concel = '取消';
  static const String arrived_bus = '已到站: ';
  static const String coming_bus = '即将到站: ';
  static const String my_infos = '本应用提供搜索北京市公交信息，查询实时北京公交到站信息的功能，您可以保存常用的路线信息，简化查询流程。数据来源于';
  static const String beijin_bus = '北京公交网';
  static const String beijin_bus_addr = 'http://www.bjbus.com/home/index.php';
  static const String project_introduce = '应用简介';
  static const String project_address = '项目地址';
  static const String project_github = 'github地址\n';
  static const String project_github_address = 'https://github.com/bingocode/flutter_bingocode';
  static const String project_juejing = '博客地址';
  static const String project_juejing_address = 'https://juejin.im/user/598c1964f265da3e190da56e';
  static const String comment = '用户反馈';
  static const String version_info = '版本信息';
  static const String version = '1.0';
  static const String submit = '提交';
}